namespace RagApi.Models;

/// <summary>
/// Represents a job application in the recruitment system
/// </summary>
public class Application
{
    /// <summary>
    /// Unique identifier for the application
    /// </summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Reference to the candidate who submitted the application
    /// </summary>
    public string CandidateId { get; set; } = string.Empty;

    /// <summary>
    /// Reference to the job posting being applied to
    /// </summary>
    public string JobPostingId { get; set; } = string.Empty;

    /// <summary>
    /// Date when the application was submitted
    /// </summary>
    public DateTime AppliedDate { get; set; }

    /// <summary>
    /// Current status of the application
    /// </summary>
    public string Status { get; set; } = string.Empty;

    /// <summary>
    /// Match score generated by AI analysis (0-100)
    /// </summary>
    public decimal? MatchScore { get; set; }

    /// <summary>
    /// Detailed analysis of candidate match with job requirements
    /// </summary>
    public string MatchAnalysis { get; set; } = string.Empty;

    /// <summary>
    /// Additional notes about the application
    /// </summary>
    public string Notes { get; set; } = string.Empty;

    /// <summary>
    /// When the application was created
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// When the application was last updated
    /// </summary>
    public DateTime UpdatedAt { get; set; }

    /// <summary>
    /// Navigation property to the candidate
    /// </summary>
    public Candidate? Candidate { get; set; }

    /// <summary>
    /// Navigation property to the job posting
    /// </summary>
    public JobPosting? JobPosting { get; set; }

    /// <summary>
    /// Navigation property to interviews for this application
    /// </summary>
    public ICollection<Interview> Interviews { get; set; } = new List<Interview>();

    /// <summary>
    /// Checks if the application is in an active state
    /// </summary>
    public bool IsActive => Status == "New" || Status == "InReview" || Status == "Interview";
}