using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace RagMaui.Models
{
    /// <summary>
    /// Response from the RAG system containing an answer and source references
    /// </summary>
    public class RagResponse
    {
        /// <summary>
        /// The answer generated by the AI
        /// </summary>
        public string Answer { get; set; }

        /// <summary>
        /// Source documents that were used to generate the answer
        /// </summary>
        public List<SearchResult> SourceResults { get; set; } = new List<SearchResult>();
    }

    /// <summary>
    /// Represents a search result used as context for the RAG system
    /// </summary>
    public class SearchResult
    {
        /// <summary>
        /// Document identifier
        /// </summary>
        public string DocumentId { get; set; }

        /// <summary>
        /// Title of the document
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// Content snippet from the document
        /// </summary>
        public string Content { get; set; }

        /// <summary>
        /// Relevance score for this result
        /// </summary>
        public double Score { get; set; }
    }

    /// <summary>
    /// Represents a conversation between a user and the RAG system
    /// </summary>
    public class Conversation
    {
        /// <summary>
        /// Unique identifier for the conversation
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// Title of the conversation
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// When the conversation was created
        /// </summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// When the conversation was last updated
        /// </summary>
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Messages in this conversation
        /// </summary>
        public List<Message> Messages { get; set; } = new List<Message>();
    }

    /// <summary>
    /// Represents a message in a conversation
    /// </summary>
    public class Message
    {
        /// <summary>
        /// Unique identifier for the message
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// ID of the conversation this message belongs to
        /// </summary>
        public string ConversationId { get; set; }

        /// <summary>
        /// Type of the message (user or system)
        /// </summary>
        public MessageType Type { get; set; }

        /// <summary>
        /// Content of the message
        /// </summary>
        public string Content { get; set; }

        /// <summary>
        /// Search results as a parsed object (not available directly from API)
        /// </summary>
        [JsonIgnore]
        public List<SearchResult> SearchResults { get; set; } = new List<SearchResult>();

        /// <summary>
        /// When the message was created
        /// </summary>
        public DateTime CreatedAt { get; set; }
    }

    /// <summary>
    /// Defines the possible types of messages
    /// </summary>
    public enum MessageType
    {
        /// <summary>
        /// Message from the user
        /// </summary>
        User,

        /// <summary>
        /// Message from the system
        /// </summary>
        System
    }

    /// <summary>
    /// Response for document upload operations
    /// </summary>
    public class UploadDocumentResponse
    {
        /// <summary>
        /// ID of the uploaded document
        /// </summary>
        public string DocumentId { get; set; }

        /// <summary>
        /// Success message
        /// </summary>
        public string Message { get; set; }
    }

    /// <summary>
    /// Generic API response wrapper
    /// </summary>
    public class ApiResponse<T>
    {
        /// <summary>
        /// Indicates if there was an error
        /// </summary>
        public bool Error { get; set; }

        /// <summary>
        /// Optional message
        /// </summary>
        public string Message { get; set; }

        /// <summary>
        /// The response data
        /// </summary>
        public T Data { get; set; }
    }
}
